# Generated by Django 4.0 on 2022-01-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_magaz_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='magaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='api.magaz'),
        ),
    ]
